// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7klcGSO-Eduykd_KySRZQayPHloktT84',
    appId: '1:445590518142:web:c856890a7cb68119111b2f',
    messagingSenderId: '445590518142',
    projectId: 'covoit-benin',
    authDomain: 'covoit-benin.firebaseapp.com',
    databaseURL: 'https://covoit-benin-default-rtdb.firebaseio.com',
    storageBucket: 'covoit-benin.appspot.com',
    measurementId: 'G-V53TMX8JW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArLkafDvJtC6Y2EbbrCup3qi1DuPiagLg',
    appId: '1:445590518142:android:07cab68f2fc2ca18111b2f',
    messagingSenderId: '445590518142',
    projectId: 'covoit-benin',
    databaseURL: 'https://covoit-benin-default-rtdb.firebaseio.com',
    storageBucket: 'covoit-benin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6mIHShjrPP0A0FJgfLo4N3Y3PtCvn1y8',
    appId: '1:445590518142:ios:9f1908d57283d181111b2f',
    messagingSenderId: '445590518142',
    projectId: 'covoit-benin',
    databaseURL: 'https://covoit-benin-default-rtdb.firebaseio.com',
    storageBucket: 'covoit-benin.appspot.com',
    iosBundleId: 'com.example.covoitBenin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6mIHShjrPP0A0FJgfLo4N3Y3PtCvn1y8',
    appId: '1:445590518142:ios:7aff839b7416b909111b2f',
    messagingSenderId: '445590518142',
    projectId: 'covoit-benin',
    databaseURL: 'https://covoit-benin-default-rtdb.firebaseio.com',
    storageBucket: 'covoit-benin.appspot.com',
    iosBundleId: 'com.example.covoitBenin.RunnerTests',
  );
}
